[package]
name = "aztec_lend"
type = "contract"
authors = [""]
compiler_version = "0.16.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.9.0", directory="yarn-project/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.9.0", directory="yarn-project/aztec-nr/authwit" }